### PR TITLE
Extend channel limit to include AMELLIE fibres

### PR DESCRIPTION
**Pull request by mnirkko**
Changed hard-coded channel limit from 96 to 105 in order to pulse AMELLIE fibres. It seems that the iterator is 0 < it < N, but we didn't notice this earlier because channel 96 only has a PIN readout (no LED).

### CODE REVIEW

**Comment by EdLeming** [comment]
Thanks for this Martti. I believe we have a slight problem in this repo in that I believe the current master doesn't work underground. Could you and @Mark--S  please confirm? (I think we're running off an old commit...)

Once we fix that, I can pull this through

**Comment by mnirkko** [comment]
Yes, I'm afraid this is correct, Mark reverted this when he was last at SNOLAB. Quoting him:
> There was an issue with making the PIN readings.
> The server would just exit the pulsing if it made a PIN reading and there was no reading availiable.
> And it would try to make a reading after about a couple of seconds.
We should investigate which change caused this and fix it asap, so we can use up-to-date versions.

**Comment by mnirkko** [comment]
So I've merged my master branch with snoplus/master, and it looks identical to the UG changes now (some weird thing with a tab/space replacement, but never mind that). I think we should merge everything back into snoplus/master and go from there.

**Comment by mnirkko** [comment]
Superceded by PR #41 - closing.

**Pull request closed without merging**
