### PR TITLE
Updated pause time

### PR DESCRIPTION
**Pull request by Mark--S**

### CODE REVIEW

**Comment by EdLeming** [comment]
Hey Mark. What;s this for?

**Comment by Mark--S** [comment]
This is the fix to stop the crashing yesterday.  The server was seeing unexpected buffer output as there wasn't enough delay in obtaining the PIN readings at the end of a subrun.

The changes in the stop function were made before as I think the code would throw an unexpected buffer content if we didn't read it before sending the other commands. I think we forgot to merge them into master.

**Comment by mnirkko** [comment]
Beware that in tellie.cfg, the parameter "short_pause" was changed from 0.1 to 0.3 - this parameter is used very often, so the code will run a lot slower... do we want this?

**Comment by mnirkko** [comment]
This can be closed now, since the changes here were implemented in #37.

**Pull request closed without merging**
