### PR TITLE
Multiple channel bug fix

### PR DESCRIPTION
**Pull request by Mark--S**
This PR should fix the issues that were seen when TELLIE was pulsing multiple single channels. Whenever the stop command is now sent to the server the channel will be cleared on the PIC chip and all the channel and global settings will be cleared from the python code.

I've also added a 0.2s delay when reading the PIN readings as I was seeing an issue on the test setup where the server was trying to read the buffer when only half the PIN reading had been written to it.

### CODE REVIEW

**Comment by EdLeming** [comment]
Sweet. Have you tested at Sussex? It would be worth firing a couple of channels in sequence at full intensity and having a look to see if you can observe light both before and after this fix is applied.

**Comment by Mark--S** [comment]
I've ran a script to test the server. (See Below)
[Code](https://gist.github.com/Mark--S/b07da8f0d5c8daacb960a26dc91da5e4)

We weren't able to reproduce the multiple firing at Sussex. This could be because you're pulsing different channels on the same box. Looking at the screen shot it seems that in the previous runs we were pulsing channels 31 then 91.

**Comment by EdLeming** [comment]
Hmmm, interesting that you can't reproduce. I think we requested 4-5 different tellie channels over the course of testing (we can use the couchdb files to confirm). 

My hypothesis, although I haven't had time to check yet (sorry, I'm in chemistry labs all day today), is that the channels relating to fibres 1 & 55 had 1000 photon set points at significantly higher IPW than the others. Therefore for any given IPW setting these channels were dominating the light output, hiding the other spots. If you have time it might be worth looking into this.

**Comment by EdLeming** [comment]
@Mark--S. Have you looked into this in an further detail? Are you expecting to add more commits or can we consider this PR stable?

**Comment by Mark--S** [comment]
I wasn't able to produce the multiple channel firing at sussex. I think we should test this underground and see if we see the multiple channels firing.

**Pull request merged**
