### PR TITLE
Merge underground changes into master

### PR DESCRIPTION
**Pull request by mnirkko**
I believe we should merge the UG changes (= what we are currently running TELLIE with) into the master branch, to make sure everyone is on the same page.

Looks to me like the ORCA bug (multiple "Nones") as well as a few minor issues (missing parameters etc.) are all fixed in this version.

### CODE REVIEW

**Comment by EdLeming** [comment]
Logic is sensible, however it says there are no differences between master and this branch. Perhaps they've already been synced?

**Comment by mnirkko** [comment]
I know, I think Mark's commit "Fix conflicts" took care of this when merging into his UGchanges branch. But it was never pushed upstream?

**Comment by EdLeming** [comment]
Hmmmm, all of this was done since the last commit in the snoplus/tellie repo's history. I'm not sure exactly what's going on but I'm happy to pull through. 

Have you been running on the Mark--S/undergroundChanges branch for recent testing? It might be worth adding a check to the server launch code tell the user if they're not on master when launching. That should make it difficult for people to from test branches by mistake.

**Comment by mnirkko** [comment]
Yes, I believe the branch Mark--S/undergroundChanges has been running on SNODROP for at least a year now. Such a check may be worth writing indeed.

**Comment by mnirkko** [comment]
@EdLeming please merge this PR before the other one I just proposed (#44).

**Pull request merged**
