### PR TITLE
Tellie control bug fixes

### PR DESCRIPTION
**Pull request by Mark--S**

### CODE REVIEW

**Comment by EdLeming** [comment]
@Mark--S. Does this PR address all the issues we spoke about at lunch?

**Comment by EdLeming** [comment]
it looks like there are slightly different changes in core/serial_command and core/tellie_server

**Comment by Mark--S** [comment]
So this PR fixes three issues.

- Swaps the average PIN reading command for upper and lower boxes around . This is the fix for not seeing the PIN readings on the upper boxes in slave mode
- The disable external trigger is called at the initialization of the serial command and when the stop() method is called.
-When the PIN reading is read out as 0 the code would throw an error. The buffer contents had the form 0 .0000000. The lack of a leading 0 on the rms caused the regex expression to fail to parse the pins.

I think I should test it underground tomorrow, then when I've tested it you can approve the PR

**Comment by EdLeming** [comment]
@Mark--S. Great! Thanks.

**Comment by Mark--S** [comment]
I've done some testing with the test box at Sussex  around with the TELLIE server i.e. sending multiple jobs to the server and killing the server when pulsing. The changes make sure that TELLIE stops pulsing in these cases.

**Comment by Mark--S** [comment]
This PR also appears to fix the issue with the unwanted pulsing when setting a channel.

**Comment by EdLeming** [comment]
This looks good, thanks! Are there any further changes you're planning on adding? If not I'll get it pulled in.

**Comment by Mark--S** [comment]
I've just one last change increasing the sleep time between buffer readings, I sometimes found the code would crash out as it wasn't giving the PIC chip the time to write to the buffer.

**Pull request merged**
